<?php

namespace App\Services\Studio;

use App\Jobs\ProcessImageJob;
use App\Models\ShootFile;
use App\Models\StudioWorkspace;
use App\Services\Media\MediaStorage;
use App\Support\LockedWrite;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

/** AI results are delivery-ready media; original uploads and human review stay untouched. */
class WorkspaceShootPublisher
{
    public function publish(StudioWorkspace $workspace, array $item, array $output, string $outputKey): ?ShootFile
    {
        if (empty($item['shootId'])) {
            return null;
        }
        $source = ShootFile::where('shoot_id', $item['shootId'])->find($item['fileId'] ?? ($item['stackFileIds'][0] ?? 0));
        if (! $source) {
            throw new \App\Exceptions\StudioProviderException('The original photo is no longer available in this shoot.');
        }
        $key = $workspace->id.':'.$outputKey;
        $existing = ShootFile::where('shoot_id', $source->shoot_id)->where('ai_editing_metadata->output_key', $key)->first();
        if ($existing) {
            return $existing;
        }
        $treatment = ShootFile::normalizeTreatment(str_replace('-', '_', $workspace->preset_id));
        $category = $treatment ?? ($source->media_type === 'drone' ? 'drone' : 'photo');
        $base = Str::slug(pathinfo($source->filename, PATHINFO_FILENAME)) ?: 'photo';
        $filename = $base.'-'.$workspace->preset_id.'-'.substr(hash('sha256', $key), 0, 16).'.jpg';
        $path = "shoots/{$source->shoot_id}/edited/{$filename}";
        $bytes = Storage::disk('public')->get($output['path']);
        if (! $bytes || ! app(MediaStorage::class)->put($path, $bytes)) {
            throw new \RuntimeException('The edited photo could not be saved to the shoot.');
        }

        return LockedWrite::run(fn () => DB::transaction(function () use ($workspace, $source, $key, $category, $treatment, $filename, $path, $bytes, $output) {
            $existing = ShootFile::where('shoot_id', $source->shoot_id)->where('ai_editing_metadata->output_key', $key)->first();
            if ($existing) {
                return $existing;
            }
            $file = ShootFile::create([
                'shoot_id' => $source->shoot_id, 'shoot_service_id' => $source->shoot_service_id,
                'filename' => $filename, 'stored_filename' => $filename, 'path' => $path, 'storage_path' => $path,
                'file_type' => 'image/jpeg', 'mime_type' => 'image/jpeg', 'media_type' => $category, 'treatment' => $treatment,
                'file_size' => strlen($bytes), 'uploaded_by' => $workspace->created_by, 'uploaded_at' => now(),
                'workflow_stage' => ShootFile::STAGE_VERIFIED, 'verified_at' => now(), 'moved_to_completed_at' => now(),
                'is_ai_edited' => true, 'required_for_editing' => false,
                'scan_status' => ShootFile::SCAN_STATUS_CLEAN, 'scan_result' => 'generated by AI editing', 'scanned_at' => now(),
                'ai_editing_metadata' => ['provider' => data_get($workspace->operation, 'routing.'.$workspace->preset_id.'.provider'),
                    'source_file_id' => $source->id, 'workspace_id' => $workspace->id, 'parent_workspace_id' => $workspace->parent_workspace_id,
                    'output_key' => $key, 'completed_at' => now()->toIso8601String(),
                    'variation_id' => $output['vsai']['variationId'] ?? null, 'variation_type' => $output['vsai']['type'] ?? null,
                    'result_index' => $output['vsai']['resultIndex'] ?? null, 'render_id' => $output['vsai']['renderId'] ?? null, 'label' => $output['label'] ?? null],
            ]);
            ProcessImageJob::dispatch($file)->afterCommit();
            return $file;
        }), 'studio.publish');
    }

    public function completeServices(StudioWorkspace $workspace): void
    {
        if (! $workspace->shoot_id || $workspace->status !== 'completed') {
            return;
        }
        foreach ($workspace->shoot_service_ids ?? [] as $serviceId) {
            $pending = StudioWorkspace::where('shoot_id', $workspace->shoot_id)->where('shoot_dispatch_key', $workspace->shoot_dispatch_key)
                ->where('status', '!=', 'completed')->get()->contains(fn ($project) => in_array($serviceId, $project->shoot_service_ids ?? []));
            if (! $pending) {
                DB::table('shoot_service')->where('shoot_id', $workspace->shoot_id)->where('service_id', $serviceId)->whereNull('editor_id')
                    ->update(['editing_completed_at' => now(), 'updated_at' => now()]);
            }
        }
        if ($workspace->shoot_dispatch_key === 'intake'
            && ! StudioWorkspace::where('shoot_id', $workspace->shoot_id)->where('shoot_dispatch_key', 'intake')->where('status', '!=', 'completed')->exists()) {
            $shoot = \App\Models\Shoot::find($workspace->shoot_id);
            $hasHumanWork = DB::table('shoot_service')->where('shoot_id', $workspace->shoot_id)
                ->where(fn ($query) => $query->whereNotNull('editor_id')->orWhereNotNull('video_editor_id'))->exists();
            if ($shoot?->status === \App\Models\Shoot::STATUS_EDITING
                && (! $hasHumanWork || app(\App\Services\Shoots\ShootEditingAssignmentService::class)->allTrackedLanesReady($shoot))) {
                $shoot->update(['status' => \App\Models\Shoot::STATUS_READY, 'workflow_status' => \App\Models\Shoot::STATUS_READY, 'editing_completed_at' => now()]);
            }
        }
    }
}
