<?php

namespace App\Services\ReproAi;

class IntentRegistry
{
    /**
     * @return array<int, array<string, mixed>>
     */
    public function all(): array
    {
        return [
            [
                'name' => 'book_shoot',
                'min_confidence' => 1.3,
                'min_keyword_matches' => 1,
                'required_groups' => [
                    ['book ', 'book a', 'book new', 'book another', 'schedule', 'create booking', 'set up'],
                    ['shoot', 'session', 'booking'],
                ],
                'disqualifying_keywords' => [
                    'reschedule',
                    'cancel',
                    'manage booking',
                    'change booking',
                    'availability',
                    'check availability',
                ],
                'keywords' => [
                    'book a new shoot' => 1.4,
                    'book a shoot' => 1.2,
                    'book new shoot' => 1.3,
                    'book another shoot' => 1.2,
                    'book shoot' => 1.1,
                    'schedule a shoot' => 1.2,
                    'schedule shoot' => 1.1,
                    'schedule a session' => 1.0,
                    'book a session' => 1.0,
                    'create a booking' => 1.0,
                    'set up a shoot' => 1.1,
                    'new shoot' => 0.8,
                    'book' => 0.4,
                    'shoot' => 0.4,
                ],
                'negative_keywords' => [
                    'reschedule',
                    'cancel',
                    'manage',
                    'availability',
                    'check availability',
                ],
                'examples' => [
                    'Book a new shoot',
                    'Can you book a shoot for next week?',
                    'Schedule a shoot for 24 Ocean Ave',
                    'Create a booking for Friday',
                ],
            ],
            [
                'name' => 'manage_booking',
                'min_confidence' => 1.1,
                'min_keyword_matches' => 1,
                'required_groups' => [
                    ['reschedule', 'cancel', 'change', 'update', 'manage', 'move'],
                    ['booking', 'shoot', 'appointment', 'service', 'services'],
                ],
                'disqualifying_keywords' => [
                    'new shoot',
                    'book a new shoot',
                    'book a shoot',
                ],
                'keywords' => [
                    'manage booking' => 1.2,
                    'manage a booking' => 1.2,
                    'manage existing booking' => 1.4,
                    'change services' => 1.2,
                    'change service' => 1.1,
                    'update services' => 1.2,
                    'update service' => 1.1,
                    'reschedule' => 1.1,
                    'reschedule shoot' => 1.3,
                    'reschedule booking' => 1.3,
                    'cancel booking' => 1.3,
                    'cancel shoot' => 1.2,
                    'change booking' => 1.0,
                    'change shoot' => 0.9,
                    'change date' => 0.8,
                    'move shoot' => 0.9,
                    'update booking' => 1.0,
                    'manage' => 0.4,
                    'booking' => 0.4,
                ],
                'negative_keywords' => [
                    'new shoot',
                    'book a new shoot',
                    'book a shoot',
                    'schedule a shoot',
                ],
                'examples' => [
                    'Manage an existing booking',
                    'Reschedule my shoot',
                    'Cancel a booking',
                    'Change my shoot date',
                ],
            ],
            [
                'name' => 'edit_photos',
                'min_confidence' => 1.0,
                'min_keyword_matches' => 1,
                'required_groups' => [
                    ['edit', 'enhance', 'autoenhance', 'retouch', 'ai edit', 'submit photos'],
                ],
                'disqualifying_keywords' => [
                    'book',
                    'reschedule',
                    'cancel booking',
                    'availability',
                ],
                'keywords' => [
                    'edit photos' => 1.4,
                    'edit my photos' => 1.4,
                    'enhance photos' => 1.3,
                    'enhance my photos' => 1.3,
                    'ai edit' => 1.2,
                    'ai editing' => 1.2,
                    'autoenhance' => 1.2,
                    'submit for editing' => 1.2,
                    'submit photos' => 1.1,
                    'send to autoenhance' => 1.2,
                    'retouch photos' => 1.1,
                    'sky replace' => 0.9,
                    'sky replacement' => 0.9,
                    'window pull' => 0.9,
                    'vertical correction' => 0.9,
                    'edit' => 0.4,
                    'enhance' => 0.4,
                ],
                'negative_keywords' => [
                    'book',
                    'reschedule',
                    'availability',
                ],
                'examples' => [
                    'Edit photos for 123 Main St',
                    'Enhance my photos at 456 Oak Ave',
                    'Submit photos for AI editing',
                    'Autoenhance 24 Ocean Avenue',
                ],
            ],
            [
                'name' => 'availability',
                'min_confidence' => 1.0,
                'min_keyword_matches' => 1,
                'required_groups' => [
                    ['availability', 'available', 'slots', 'openings', 'next available', 'check availability'],
                ],
                'keywords' => [
                    'check availability' => 1.2,
                    'photographer availability' => 1.1,
                    'availability' => 0.9,
                    'any slots' => 0.9,
                    'next available' => 0.8,
                    'time slots' => 0.8,
                    'openings' => 0.7,
                    'slots' => 0.7,
                    'available' => 0.5,
                ],
                'negative_keywords' => [
                    'reschedule',
                    'cancel',
                ],
                'examples' => [
                    'Check photographer availability',
                    'Any slots next Thursday?',
                    'Is anyone available tomorrow?',
                ],
            ],
            [
                'name' => 'support_faq',
                'min_confidence' => 1.0,
                'min_keyword_matches' => 1,
                'required_groups' => [
                    [
                        'faq', 'help', 'question', 'support', 'human', 'representative',
                        'speak to', 'talk to', 'ticket', 'turnaround', 'copyright',
                        'who owns', 'password', 'log in', 'login', 'download', 'upload to mls',
                        'prepare', 'photo ready', 'contact', 'phone number', 'email address',
                    ],
                ],
                'disqualifying_keywords' => [
                    'book a shoot',
                    'book a new shoot',
                    'reschedule',
                    'cancel booking',
                    'cancel my booking',
                    'check availability',
                    'edit photos',
                    'enhance photos',
                ],
                'keywords' => [
                    'speak to a human' => 1.4,
                    'talk to a human' => 1.4,
                    'speak to a representative' => 1.4,
                    'support ticket' => 1.3,
                    'create a ticket' => 1.2,
                    'raise a ticket' => 1.2,
                    'copyright' => 1.2,
                    'who owns' => 1.1,
                    'turnaround' => 1.2,
                    'how long' => 1.0,
                    'reset password' => 1.1,
                    'forgot password' => 1.1,
                    'how do i download' => 1.2,
                    'download my photos' => 1.1,
                    'download my images' => 1.1,
                    'upload to mls' => 1.1,
                    'how do i upload' => 1.0,
                    'prepare for the shoot' => 1.1,
                    'photo ready' => 1.0,
                    'view faq' => 1.2,
                    'faq' => 1.0,
                    'help' => 0.6,
                    'question' => 0.6,
                    'contact' => 0.7,
                    'human' => 0.8,
                    'representative' => 0.9,
                ],
                'negative_keywords' => [
                    'book a shoot',
                    'reschedule',
                    'cancel',
                    'availability',
                ],
                'examples' => [
                    'How long until I get my photos?',
                    'Who owns the copyright to the images?',
                    'How do I reset my portal password?',
                    'I want to speak to a human',
                    'Create a support ticket',
                    'How do I upload to the MLS?',
                ],
            ],
        ];
    }
}
