<?php

return [
    'roles' => [
        [
            'id' => 'superadmin',
            'label' => 'Super Admin',
            'description' => 'Full platform access across every area.',
            'locked' => true,
        ],
        [
            'id' => 'admin',
            'label' => 'Admin',
            'description' => 'Operational access across booking, production, and finance.',
            'locked' => false,
        ],
        [
            'id' => 'editing_manager',
            'label' => 'Editing Manager',
            'description' => 'Production oversight with editing-focused controls.',
            'locked' => false,
        ],
        [
            'id' => 'salesRep',
            'label' => 'Sales Rep',
            'description' => 'Client growth, sales activity, and rep-facing workflows.',
            'locked' => false,
        ],
        [
            'id' => 'photographer',
            'label' => 'Photographer',
            'description' => 'Assigned shoots, media upload, and availability.',
            'locked' => false,
        ],
        [
            'id' => 'editor',
            'label' => 'Editor',
            'description' => 'Editing jobs, review flow, and delivery support.',
            'locked' => false,
        ],
        [
            'id' => 'client',
            'label' => 'Client',
            'description' => 'Client dashboard, billing, delivery, and messaging.',
            'locked' => false,
        ],
    ],
    'groups' => [
        [
            'id' => 'core-navigation',
            'label' => 'Core Navigation',
            'description' => 'Primary pages, route access, and top-level tools.',
            'items' => [
                [
                    'resource' => 'dashboard',
                    'action' => 'view',
                    'label' => 'Dashboard',
                    'description' => 'Open the main dashboard.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'salesRep', 'photographer', 'editor', 'client'],
                ],
                [
                    'resource' => 'book-shoot',
                    'action' => 'create',
                    'label' => 'Book Shoot',
                    'description' => 'Open and use the booking flow.',
                    'default_roles' => ['superadmin', 'admin', 'salesRep', 'client'],
                ],
                [
                    'resource' => 'shoots',
                    'action' => 'view',
                    'label' => 'Shoot History',
                    'description' => 'Access shoot history and shoot details.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'salesRep', 'photographer', 'editor', 'client'],
                ],
                [
                    'resource' => 'invoices',
                    'action' => 'view',
                    'label' => 'Invoices Page',
                    'description' => 'Open invoice history and invoice details.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'salesRep', 'client'],
                ],
                [
                    'resource' => 'accounting',
                    'action' => 'view',
                    'label' => 'Accounting / Billing',
                    'description' => 'Access accounting, billing, earnings, or pay views.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'salesRep', 'photographer', 'editor', 'client'],
                ],
                [
                    'resource' => 'accounts',
                    'action' => 'view',
                    'label' => 'Accounts',
                    'description' => 'Access the Accounts page and account administration tools.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'salesRep'],
                ],
                [
                    'resource' => 'account-linking',
                    'action' => 'view',
                    'label' => 'Account Linking',
                    'description' => 'Open account linking tools in Accounts.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'salesRep'],
                ],
                [
                    'resource' => 'account-linking',
                    'action' => 'update',
                    'label' => 'Manage Account Linking',
                    'description' => 'Create, update, and remove account links.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'salesRep'],
                ],
                [
                    'resource' => 'permissions-manager',
                    'action' => 'view',
                    'label' => 'Permissions Manager',
                    'description' => 'Open the permissions management interface.',
                    'default_roles' => ['superadmin', 'admin'],
                ],
                [
                    'resource' => 'permissions-manager',
                    'action' => 'update',
                    'label' => 'Edit Permissions',
                    'description' => 'Save permission changes for roles.',
                    'default_roles' => ['superadmin', 'admin'],
                ],
                [
                    'resource' => 'availability',
                    'action' => 'view',
                    'label' => 'Availability',
                    'description' => 'Open the availability management page.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'salesRep', 'photographer'],
                ],
                [
                    'resource' => 'reports',
                    'action' => 'view',
                    'label' => 'Reports',
                    'description' => 'Open reporting and analytics pages.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager'],
                ],
                [
                    'resource' => 'settings',
                    'action' => 'view',
                    'label' => 'Settings',
                    'description' => 'Open the Settings page.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'salesRep', 'photographer', 'editor', 'client'],
                ],
                [
                    'resource' => 'settings',
                    'action' => 'update',
                    'label' => 'Update Own Settings',
                    'description' => 'Save settings and profile-related updates.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'salesRep', 'photographer', 'editor', 'client'],
                ],
                [
                    'resource' => 'profile',
                    'action' => 'view',
                    'label' => 'Profile',
                    'description' => 'Open the dedicated profile page.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'salesRep', 'photographer', 'editor', 'client'],
                ],
                [
                    'resource' => 'portal',
                    'action' => 'view',
                    'label' => 'Exclusive Listings',
                    'description' => 'Open exclusive listings and listing detail pages.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'salesRep', 'client'],
                ],
                [
                    'resource' => 'integrations',
                    'action' => 'view',
                    'label' => 'Integrations',
                    'description' => 'Open integrations pages and integration settings.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager'],
                ],
                [
                    'resource' => 'scheduling-settings',
                    'action' => 'view',
                    'label' => 'Scheduling Settings',
                    'description' => 'Open scheduling configuration pages.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager'],
                ],
                [
                    'resource' => 'tour-branding',
                    'action' => 'view',
                    'label' => 'Tour Branding',
                    'description' => 'Open tour branding tools.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager'],
                ],
                [
                    'resource' => 'coupons',
                    'action' => 'view',
                    'label' => 'Coupons',
                    'description' => 'Open the coupons tab and coupon tools.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'salesRep'],
                ],
                [
                    'resource' => 'coupons',
                    'action' => 'create',
                    'label' => 'Create Coupons',
                    'description' => 'Create and manage coupons.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'salesRep'],
                ],
                [
                    'resource' => 'watermark-settings',
                    'action' => 'view',
                    'label' => 'Watermark Settings',
                    'description' => 'Open watermark settings.',
                    'default_roles' => ['superadmin'],
                ],
                [
                    'resource' => 'robbie-settings',
                    'action' => 'view',
                    'label' => 'Robbie AI Settings',
                    'description' => 'Open Robbie AI settings.',
                    'default_roles' => ['superadmin'],
                ],
                [
                    'resource' => 'system-overview',
                    'action' => 'view',
                    'label' => 'System Overview',
                    'description' => 'Open the superadmin system overview and observability workspace.',
                    'default_roles' => ['superadmin'],
                ],
                [
                    'resource' => 'ai-editing',
                    'action' => 'view',
                    'label' => 'AI Editing',
                    'description' => 'Open the AI editing workspace.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager'],
                ],
                [
                    'resource' => 'cubicasa-scanning',
                    'action' => 'view',
                    'label' => 'CubiCasa Scanning',
                    'description' => 'Open CubiCasa scanning tools.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'photographer'],
                ],
                [
                    'resource' => 'robbie',
                    'action' => 'view',
                    'label' => 'Chat With Robbie',
                    'description' => 'Open the Robbie chat assistant.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'salesRep', 'client'],
                ],
            ],
        ],
        [
            'id' => 'dashboard-sections',
            'label' => 'Dashboard Sections',
            'description' => 'Widgets, panels, and role-specific dashboard experiences.',
            'items' => [
                [
                    'resource' => 'dashboard-admin',
                    'action' => 'view',
                    'label' => 'Admin Dashboard Layout',
                    'description' => 'Use the operations-focused dashboard layout.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager'],
                ],
                [
                    'resource' => 'dashboard-sales',
                    'action' => 'view',
                    'label' => 'Sales Dashboard Layout',
                    'description' => 'Use the sales representative dashboard layout.',
                    'default_roles' => ['salesRep'],
                ],
                [
                    'resource' => 'dashboard-photographer',
                    'action' => 'view',
                    'label' => 'Photographer Dashboard Layout',
                    'description' => 'Use the photographer dashboard layout.',
                    'default_roles' => ['photographer'],
                ],
                [
                    'resource' => 'dashboard-editor',
                    'action' => 'view',
                    'label' => 'Editor Dashboard Layout',
                    'description' => 'Use the editor dashboard layout.',
                    'default_roles' => ['editor'],
                ],
                [
                    'resource' => 'dashboard-client',
                    'action' => 'view',
                    'label' => 'Client Dashboard Layout',
                    'description' => 'Use the client dashboard layout.',
                    'default_roles' => ['client'],
                ],
                [
                    'resource' => 'dashboard-availability',
                    'action' => 'view',
                    'label' => 'Availability Widget',
                    'description' => 'Load and show availability-related dashboard data.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'salesRep'],
                ],
                [
                    'resource' => 'dashboard-editing-requests',
                    'action' => 'view',
                    'label' => 'Editing Requests Widget',
                    'description' => 'Load and show editing requests on the dashboard.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'salesRep', 'editor'],
                ],
                [
                    'resource' => 'dashboard-client-billing',
                    'action' => 'view',
                    'label' => 'Client Billing Widget',
                    'description' => 'Show billing summary cards on the client dashboard.',
                    'default_roles' => ['client'],
                ],
                [
                    'resource' => 'dashboard-quick-actions',
                    'action' => 'update',
                    'label' => 'Customize Quick Actions',
                    'description' => 'Edit dashboard quick actions.',
                    'default_roles' => ['superadmin', 'admin'],
                ],
                [
                    'resource' => 'dashboard-contact-actions',
                    'action' => 'view',
                    'label' => 'Sales Contact Actions',
                    'description' => 'Show sales-only contact actions on the dashboard.',
                    'default_roles' => ['salesRep'],
                ],
                [
                    'resource' => 'dashboard-production',
                    'action' => 'view',
                    'label' => 'Production Workflow Board',
                    'description' => 'Show production workflow and assignment boards.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager'],
                ],
            ],
        ],
        [
            'id' => 'messaging-ai',
            'label' => 'Messaging & AI',
            'description' => 'Messaging center, email, SMS, templates, automations, and AI tools.',
            'items' => [
                [
                    'resource' => 'messaging-email',
                    'action' => 'view',
                    'label' => 'Email Inbox',
                    'description' => 'Open the email inbox.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'salesRep', 'photographer', 'editor', 'client'],
                ],
                [
                    'resource' => 'messaging-compose',
                    'action' => 'create',
                    'label' => 'Compose Email',
                    'description' => 'Create and send emails.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'salesRep', 'photographer', 'editor', 'client'],
                ],
                [
                    'resource' => 'messaging-overview',
                    'action' => 'view',
                    'label' => 'Messaging Overview',
                    'description' => 'Open the messaging overview dashboard.',
                    'default_roles' => ['superadmin', 'admin'],
                ],
                [
                    'resource' => 'messaging-templates',
                    'action' => 'view',
                    'label' => 'Message Templates',
                    'description' => 'View email templates.',
                    'default_roles' => ['superadmin', 'admin'],
                ],
                [
                    'resource' => 'messaging-templates',
                    'action' => 'update',
                    'label' => 'Manage Message Templates',
                    'description' => 'Create, edit, duplicate, and delete templates.',
                    'default_roles' => ['superadmin', 'admin'],
                ],
                [
                    'resource' => 'messaging-automations',
                    'action' => 'view',
                    'label' => 'Messaging Automations',
                    'description' => 'View automation workflows.',
                    'default_roles' => ['superadmin', 'admin'],
                ],
                [
                    'resource' => 'messaging-automations',
                    'action' => 'update',
                    'label' => 'Manage Messaging Automations',
                    'description' => 'Create, edit, run, and toggle automations.',
                    'default_roles' => ['superadmin', 'admin'],
                ],
                [
                    'resource' => 'messaging-sms',
                    'action' => 'view',
                    'label' => 'SMS Center',
                    'description' => 'Open SMS threads and SMS tools.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'salesRep'],
                ],
                [
                    'resource' => 'voice-calls',
                    'action' => 'view',
                    'label' => 'Calls',
                    'description' => 'Open Telnyx AI voice calls, call logs, and voice assistant controls.',
                    'default_roles' => ['superadmin', 'admin'],
                ],
                [
                    'resource' => 'messaging-settings',
                    'action' => 'view',
                    'label' => 'Messaging Settings',
                    'description' => 'Open messaging settings.',
                    'default_roles' => ['superadmin', 'admin'],
                ],
            ],
        ],
        [
            'id' => 'billing-finance',
            'label' => 'Billing & Finance',
            'description' => 'Invoice, billing, and payment controls.',
            'items' => [
                [
                    'resource' => 'invoices',
                    'action' => 'create',
                    'label' => 'Create Invoices',
                    'description' => 'Create invoices from accounting.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager'],
                ],
                [
                    'resource' => 'invoices',
                    'action' => 'update',
                    'label' => 'Edit Invoices',
                    'description' => 'Edit invoice details and invoice state.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager'],
                ],
                [
                    'resource' => 'payments',
                    'action' => 'view',
                    'label' => 'View Payments',
                    'description' => 'View payment details and payment summaries.',
                    'default_roles' => ['superadmin', 'client'],
                ],
                [
                    'resource' => 'payments',
                    'action' => 'mark-paid',
                    'label' => 'Mark Payments As Paid',
                    'description' => 'Mark invoices as paid inside accounting.',
                    'default_roles' => ['superadmin'],
                ],
            ],
        ],
        [
            'id' => 'account-operations',
            'label' => 'Account Operations',
            'description' => 'Manage users, clients, photographers, and related admin controls.',
            'items' => [
                [
                    'resource' => 'clients',
                    'action' => 'view',
                    'label' => 'View Clients',
                    'description' => 'Access client records and client details.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'salesRep', 'photographer'],
                ],
                [
                    'resource' => 'clients',
                    'action' => 'create',
                    'label' => 'Create Clients',
                    'description' => 'Create new client accounts.',
                    'default_roles' => ['superadmin', 'admin', 'salesRep'],
                ],
                [
                    'resource' => 'clients',
                    'action' => 'update',
                    'label' => 'Update Clients',
                    'description' => 'Edit client account details.',
                    'default_roles' => ['superadmin', 'admin', 'salesRep'],
                ],
                [
                    'resource' => 'photographers',
                    'action' => 'view',
                    'label' => 'View Photographers',
                    'description' => 'Access photographer lists and selectors.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'salesRep', 'client'],
                ],
            ],
        ],
        [
            'id' => 'shoot-delivery',
            'label' => 'Shoot, Media & Delivery',
            'description' => 'Shoot details, media visibility, notes, requests, tours, and delivery controls.',
            'items' => [
                [
                    'resource' => 'media',
                    'action' => 'view',
                    'label' => 'View Media',
                    'description' => 'View shoot media.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'photographer', 'editor', 'client'],
                ],
                [
                    'resource' => 'media',
                    'action' => 'upload',
                    'label' => 'Upload Media',
                    'description' => 'Upload or attach shoot media.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'photographer', 'editor', 'client'],
                ],
                [
                    'resource' => 'media',
                    'action' => 'download',
                    'label' => 'Download Media',
                    'description' => 'Download individual or grouped media.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'client'],
                ],
                [
                    'resource' => 'raw-media',
                    'action' => 'view',
                    'label' => 'View Raw Media',
                    'description' => 'Access raw or uploaded media sets.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'photographer', 'editor'],
                ],
                [
                    'resource' => 'edited-media',
                    'action' => 'view',
                    'label' => 'View Edited Media',
                    'description' => 'Access edited or delivered media sets.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'editor', 'client'],
                ],
                [
                    'resource' => 'tours',
                    'action' => 'view',
                    'label' => 'View Tours',
                    'description' => 'View tour, video, and 3D links.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'photographer', 'editor', 'client'],
                ],
                [
                    'resource' => 'tours',
                    'action' => 'update',
                    'label' => 'Manage Tours',
                    'description' => 'Edit tour links and related settings.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'editor'],
                ],
                [
                    'resource' => 'requests',
                    'action' => 'view',
                    'label' => 'View Requests',
                    'description' => 'Open the requests area on shoot details.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'client'],
                ],
                [
                    'resource' => 'notes',
                    'action' => 'view',
                    'label' => 'View Shoot Notes',
                    'description' => 'Read general shoot notes.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'photographer', 'editor', 'client'],
                ],
                [
                    'resource' => 'company-notes',
                    'action' => 'view',
                    'label' => 'View Company Notes',
                    'description' => 'Read internal company notes.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager'],
                ],
                [
                    'resource' => 'editing-notes',
                    'action' => 'view',
                    'label' => 'View Editing Notes',
                    'description' => 'Read editing notes.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'editor'],
                ],
                [
                    'resource' => 'editing-notes',
                    'action' => 'update',
                    'label' => 'Update Editing Notes',
                    'description' => 'Create and edit editing notes.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager'],
                ],
                [
                    'resource' => 'photographer-notes',
                    'action' => 'view',
                    'label' => 'View Photographer Notes',
                    'description' => 'Read photographer notes.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'photographer'],
                ],
                [
                    'resource' => 'photographer-notes',
                    'action' => 'update',
                    'label' => 'Update Photographer Notes',
                    'description' => 'Create and edit photographer notes.',
                    'default_roles' => ['superadmin', 'admin', 'editing_manager', 'photographer'],
                ],
            ],
        ],
    ],
];
